### ISSUE TITLE
Rozwiązanie

### ISSUE THREAD

**Issue by maddox321** [pawelgorka/badania-operacyjne#1]
http://pawelgorka.gitbooks.io/badania-operacyjne/content/kolokwia/2015/pierwszy-termin/01/01.html

do powyzszego zadania znalazłem rozwiązanie
robisz nierówność:
150U - 1000S > 0
150U > 1000S
co nam daje: 
3ro z tabeli > S 

dzięki temu odrazu znajdujemy zaleznosc w naszym zadaniu, że ro musi byc rowne przynajmniej 1,1 i teraz szukamy już tylko odpowiedniej wartości dla L czyli w naszym przypadku L<=2

**Comment by pawelgorka** [comment]
masz rację dzięki. - już jest poprawione.
