### ISSUE TITLE
Kolokwium 2015 - zadanie 3

### ISSUE THREAD

**Issue by kanguro** [pawelgorka/badania-operacyjne#11]
http://pawelgorka.gitbooks.io/badania-operacyjne/content/kolokwia/2015/pierwszy-termin/03/03.html

"note: można interpretować system jako system M/M/1 dlatego mogę stosować wzór na L"

Czy to jest potwierdzona informacja? Definicja systemu M/M/1 z Wikipedii:
system kolejkowy, w którym [W1] >>rozkład czasu pomiędzy kolejnymi zgłoszeniami do systemu<< oraz [W2] >>rozkład czasu obsługi pojedynczego zgłoszenia<< są >>rozkładami wykładniczymi<<, istnieje jedno stanowisko obsługi i nieskończenie długa kolejka.

[W2] faktycznie jest wykładnicze, to wynika z treści zadania ("wykładniczy rozkład wymagań zgłoszeń").
Ale [W1] to rozkład Poissona - to chyba nie jest rozkład wykładniczy?

**Comment by pawelgorka** [comment]
nie to nie jest potwierdzona informacja

**Comment by kanguro** [comment]
Inne źródło: http://staff.um.edu.mt/jskl1/simweb/mm1.htm

The M/M/1 system is made of a Poisson arrival, one exponential (Poisson) server, FIFO (or not specified) queue of unlimited capacity and unlimited customer population.

Zamykam.
